In [21]:
# Import Modules
import pandas as pd

# Read in the data
dat = pd.read_csv("Investments_Data.csv", encoding = "ISO-8859-1")

# Shows us the data types of each variable included within the study.
dat.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 54294 entries, 0 to 54293
Data columns (total 39 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   permalink             49438 non-null  object
 1   name                  49437 non-null  object
 2   homepage_url          45989 non-null  object
 3   category_list         45477 non-null  object
 4    market               45470 non-null  object
 5    funding_total_usd    49438 non-null  object
 6   status                48124 non-null  object
 7   country_code          44165 non-null  object
 8   state_code            30161 non-null  object
 9   region                44165 non-null  object
 10  city                  43322 non-null  object
 11  funding_rounds        49438 non-null  float64
 12  founded_at            38554 non-null  object
 13  founded_month         38482 non-null  object
 14  founded_quarter       38482 non-null  object
 15  founded_year          38482 non-null  float64
 16  first_funding_at      49438 non-null  object
 17  last_funding_at       49438 non-null  object
 18  seed                  49438 non-null  float64
 19  venture               49438 non-null  float64
 20  equity_crowdfunding   49438 non-null  float64
 21  undisclosed           49438 non-null  float64
 22  convertible_note      49438 non-null  float64
 23  debt_financing        49438 non-null  float64
 24  angel                 49438 non-null  float64
 25  grant                 49438 non-null  float64
 26  private_equity        49438 non-null  float64
 27  post_ipo_equity       49438 non-null  float64
 28  post_ipo_debt         49438 non-null  float64
 29  secondary_market      49438 non-null  float64
 30  product_crowdfunding  49438 non-null  float64
 31  round_A               49438 non-null  float64
 32  round_B               49438 non-null  float64
 33  round_C               49438 non-null  float64
 34  round_D               49438 non-null  float64
 35  round_E               49438 non-null  float64
 36  round_F               49438 non-null  float64
 37  round_G               49438 non-null  float64
 38  round_H               49438 non-null  float64
dtypes: float64(23), object(16)
memory usage: 16.2+ MB

In [22]:
dat.country_code.value_counts()

USA    28793
GBR     2642
CAN     1405
CHN     1239
DEU      968
       ...
LIE        1
TTO        1
MAF        1
CIV        1
UZB        1
Name: country_code, Length: 115, dtype: int64

In [24]:
dat.country_code.unique()

array(['USA', 'EST', 'GBR', 'ARG', nan, 'HKG', 'CHL', 'DEU', 'FRA', 'CHN',
       'CAN', 'AUS', 'ROM', 'NLD', 'SWE', 'RUS', 'DNK', 'IND', 'SGP',
       'NOR', 'BEL', 'IRL', 'ITA', 'ISR', 'ESP', 'THA', 'NZL', 'CZE',
       'CHE', 'BRA', 'HUN', 'JPN', 'BWA', 'KOR', 'NGA', 'FIN', 'TUR',
       'CRI', 'PRT', 'TWN', 'KHM', 'COL', 'UKR', 'LTU', 'ZAF', 'AUT',
       'PHL', 'ISL', 'BGR', 'URY', 'HRV', 'KEN', 'MEX', 'JOR', 'VNM',
       'GHA', 'PER', 'POL', 'IDN', 'PAN', 'LVA', 'ALB', 'UGA', 'LBN',
       'GRC', 'ARE', 'PAK', 'EGY', 'SVK', 'LUX', 'MYS', 'BHS', 'ARM',
       'DZA', 'MDA', 'TUN', 'NIC', 'TZA', 'CYP', 'NPL', 'BHR', 'CMR',
       'SRB', 'SAU', 'CYM', 'BRN', 'SLV', 'ECU', 'MLT', 'SVN', 'LAO',
       'TTO', 'MAR', 'MMR', 'BGD', 'DOM', 'BMU', 'LIE', 'MOZ', 'GTM',
       'AZE', 'MCO', 'ZWE', 'UZB', 'OMN', 'BLR', 'JEY', 'JAM', 'KWT',
       'MUS', 'CIV', 'SOM', 'MKD', 'GIB', 'SYC', 'MAF'], dtype=object)

In [25]:
dat.country_code == 'USA'

0         True
1         True
2        False
3        False
4         True
         ...
54289    False
54290    False
54291    False
54292    False
54293    False
Name: country_code, Length: 54294, dtype: bool

In [26]:
US_Data = dat[dat['country_code'] == 'USA']

In [27]:
US_Data.shape

(28793, 39)

In [28]:
US_Data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 28793 entries, 0 to 49437
Data columns (total 39 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   permalink             28793 non-null  object
 1   name                  28793 non-null  object
 2   homepage_url          26554 non-null  object
 3   category_list         27032 non-null  object
 4    market               27029 non-null  object
 5    funding_total_usd    28793 non-null  object
 6   status                28233 non-null  object
 7   country_code          28793 non-null  object
 8   state_code            28767 non-null  object
 9   region                28793 non-null  object
 10  city                  28730 non-null  object
 11  funding_rounds        28793 non-null  float64
 12  founded_at            23696 non-null  object
 13  founded_month         23635 non-null  object
 14  founded_quarter       23635 non-null  object
 15  founded_year          23635 non-null  float64
 16  first_funding_at      28793 non-null  object
 17  last_funding_at       28793 non-null  object
 18  seed                  28793 non-null  float64
 19  venture               28793 non-null  float64
 20  equity_crowdfunding   28793 non-null  float64
 21  undisclosed           28793 non-null  float64
 22  convertible_note      28793 non-null  float64
 23  debt_financing        28793 non-null  float64
 24  angel                 28793 non-null  float64
 25  grant                 28793 non-null  float64
 26  private_equity        28793 non-null  float64
 27  post_ipo_equity       28793 non-null  float64
 28  post_ipo_debt         28793 non-null  float64
 29  secondary_market      28793 non-null  float64
 30  product_crowdfunding  28793 non-null  float64
 31  round_A               28793 non-null  float64
 32  round_B               28793 non-null  float64
 33  round_C               28793 non-null  float64
 34  round_D               28793 non-null  float64
 35  round_E               28793 non-null  float64
 36  round_F               28793 non-null  float64
 37  round_G               28793 non-null  float64
 38  round_H               28793 non-null  float64
dtypes: float64(23), object(16)
memory usage: 8.8+ MB

In [29]:
US_Data.apply(lambda x: sum(x.isnull()), axis=0)

permalink                  0
name                       0
homepage_url            2239
category_list           1761
 market                 1764
 funding_total_usd         0
status                   560
country_code               0
state_code                26
region                     0
city                      63
funding_rounds             0
founded_at              5097
founded_month           5158
founded_quarter         5158
founded_year            5158
first_funding_at           0
last_funding_at            0
seed                       0
venture                    0
equity_crowdfunding        0
undisclosed                0
convertible_note           0
debt_financing             0
angel                      0
grant                      0
private_equity             0
post_ipo_equity            0
post_ipo_debt              0
secondary_market           0
product_crowdfunding       0
round_A                    0
round_B                    0
round_C                    0
round_D                    0
round_E                    0
round_F                    0
round_G                    0
round_H                    0
dtype: int64

In [30]:
# removing null values
ref_US_Data =US_Data.dropna(axis=0)
ref_US_Data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 20863 entries, 0 to 49437
Data columns (total 39 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   permalink             20863 non-null  object
 1   name                  20863 non-null  object
 2   homepage_url          20863 non-null  object
 3   category_list         20863 non-null  object
 4    market               20863 non-null  object
 5    funding_total_usd    20863 non-null  object
 6   status                20863 non-null  object
 7   country_code          20863 non-null  object
 8   state_code            20863 non-null  object
 9   region                20863 non-null  object
 10  city                  20863 non-null  object
 11  funding_rounds        20863 non-null  float64
 12  founded_at            20863 non-null  object
 13  founded_month         20863 non-null  object
 14  founded_quarter       20863 non-null  object
 15  founded_year          20863 non-null  float64
 16  first_funding_at      20863 non-null  object
 17  last_funding_at       20863 non-null  object
 18  seed                  20863 non-null  float64
 19  venture               20863 non-null  float64
 20  equity_crowdfunding   20863 non-null  float64
 21  undisclosed           20863 non-null  float64
 22  convertible_note      20863 non-null  float64
 23  debt_financing        20863 non-null  float64
 24  angel                 20863 non-null  float64
 25  grant                 20863 non-null  float64
 26  private_equity        20863 non-null  float64
 27  post_ipo_equity       20863 non-null  float64
 28  post_ipo_debt         20863 non-null  float64
 29  secondary_market      20863 non-null  float64
 30  product_crowdfunding  20863 non-null  float64
 31  round_A               20863 non-null  float64
 32  round_B               20863 non-null  float64
 33  round_C               20863 non-null  float64
 34  round_D               20863 non-null  float64
 35  round_E               20863 non-null  float64
 36  round_F               20863 non-null  float64
 37  round_G               20863 non-null  float64
 38  round_H               20863 non-null  float64
dtypes: float64(23), object(16)
memory usage: 6.4+ MB

In [31]:
US_Data.head()

,permalink,name,homepage_url,category_list,market,funding_total_usd,status,country_code,state_code,region,...,secondary_market,product_crowdfunding,round_A,round_B,round_C,round_D,round_E,round_F,round_G,round_H
0,/organization/waywire,#waywire,http://www.waywire.com,|Entertainment|Politics|Social Media|News|,News,"17,50,000",acquired,USA,NY,New York City,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,/organization/tv-communications,&TV Communications,http://enjoyandtv.com,|Games|,Games,"40,00,000",operating,USA,CA,Los Angeles,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,/organization/r-ranch-and-mine,-R- Ranch and Mine,NaN,|Tourism|Entertainment|Games|,Tourism,"60,000",operating,USA,TX,Dallas,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,/organization/club-domains,.Club Domains,http://nic.club/,|Software|,Software,"70,00,000",NaN,USA,FL,Ft. Lauderdale,...,0.0,0.0,0.0,7000000.0,0.0,0.0,0.0,0.0,0.0,0.0
8,/organization/004-technologies,004 Technologies,http://004gmbh.de/en/004-interact,|Software|,Software,-,operating,USA,IL,"Springfield, Illinois",...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [32]:
US_Data_test = US_Data
type(US_Data_test)

pandas.core.frame.DataFrame

In [35]:
US_Data_test.reset_index(inplace = True, drop = True)
US_Data_test.head()

,permalink,name,homepage_url,category_list,market,funding_total_usd,status,country_code,state_code,region,...,secondary_market,product_crowdfunding,round_A,round_B,round_C,round_D,round_E,round_F,round_G,round_H
0,/organization/waywire,#waywire,http://www.waywire.com,|Entertainment|Politics|Social Media|News|,News,"17,50,000",acquired,USA,NY,New York City,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,/organization/tv-communications,&TV Communications,http://enjoyandtv.com,|Games|,Games,"40,00,000",operating,USA,CA,Los Angeles,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,/organization/r-ranch-and-mine,-R- Ranch and Mine,NaN,|Tourism|Entertainment|Games|,Tourism,"60,000",operating,USA,TX,Dallas,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,/organization/club-domains,.Club Domains,http://nic.club/,|Software|,Software,"70,00,000",NaN,USA,FL,Ft. Lauderdale,...,0.0,0.0,0.0,7000000.0,0.0,0.0,0.0,0.0,0.0,0.0
4,/organization/004-technologies,004 Technologies,http://004gmbh.de/en/004-interact,|Software|,Software,-,operating,USA,IL,"Springfield, Illinois",...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [36]:
US_Data.reset_index(inplace = True, drop = True)
US_Data.head()

,permalink,name,homepage_url,category_list,market,funding_total_usd,status,country_code,state_code,region,...,secondary_market,product_crowdfunding,round_A,round_B,round_C,round_D,round_E,round_F,round_G,round_H
0,/organization/waywire,#waywire,http://www.waywire.com,|Entertainment|Politics|Social Media|News|,News,"17,50,000",acquired,USA,NY,New York City,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,/organization/tv-communications,&TV Communications,http://enjoyandtv.com,|Games|,Games,"40,00,000",operating,USA,CA,Los Angeles,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,/organization/r-ranch-and-mine,-R- Ranch and Mine,NaN,|Tourism|Entertainment|Games|,Tourism,"60,000",operating,USA,TX,Dallas,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,/organization/club-domains,.Club Domains,http://nic.club/,|Software|,Software,"70,00,000",NaN,USA,FL,Ft. Lauderdale,...,0.0,0.0,0.0,7000000.0,0.0,0.0,0.0,0.0,0.0,0.0
4,/organization/004-technologies,004 Technologies,http://004gmbh.de/en/004-interact,|Software|,Software,-,operating,USA,IL,"Springfield, Illinois",...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [37]:
US_Data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 28793 entries, 0 to 28792
Data columns (total 39 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   permalink             28793 non-null  object
 1   name                  28793 non-null  object
 2   homepage_url          26554 non-null  object
 3   category_list         27032 non-null  object
 4    market               27029 non-null  object
 5    funding_total_usd    28793 non-null  object
 6   status                28233 non-null  object
 7   country_code          28793 non-null  object
 8   state_code            28767 non-null  object
 9   region                28793 non-null  object
 10  city                  28730 non-null  object
 11  funding_rounds        28793 non-null  float64
 12  founded_at            23696 non-null  object
 13  founded_month         23635 non-null  object
 14  founded_quarter       23635 non-null  object
 15  founded_year          23635 non-null  float64
 16  first_funding_at      28793 non-null  object
 17  last_funding_at       28793 non-null  object
 18  seed                  28793 non-null  float64
 19  venture               28793 non-null  float64
 20  equity_crowdfunding   28793 non-null  float64
 21  undisclosed           28793 non-null  float64
 22  convertible_note      28793 non-null  float64
 23  debt_financing        28793 non-null  float64
 24  angel                 28793 non-null  float64
 25  grant                 28793 non-null  float64
 26  private_equity        28793 non-null  float64
 27  post_ipo_equity       28793 non-null  float64
 28  post_ipo_debt         28793 non-null  float64
 29  secondary_market      28793 non-null  float64
 30  product_crowdfunding  28793 non-null  float64
 31  round_A               28793 non-null  float64
 32  round_B               28793 non-null  float64
 33  round_C               28793 non-null  float64
 34  round_D               28793 non-null  float64
 35  round_E               28793 non-null  float64
 36  round_F               28793 non-null  float64
 37  round_G               28793 non-null  float64
 38  round_H               28793 non-null  float64
dtypes: float64(23), object(16)
memory usage: 8.6+ MB

In [38]:
US_Data.to_csv('US_StartUps_Investments_Data.csv')

In [39]:
US_Data.status.unique()

array(['acquired', 'operating', nan, 'closed'], dtype=object)

In [40]:
US_Data.status.value_counts()

operating    23985
acquired      2785
closed        1463
Name: status, dtype: int64